EXP:
  ROOT: /path/to/experiment_root
  NAME: motion_recurrent

DATA:
  ROOT: /path/to/data_root
  NUM_WORKERS: 4
  TRAIN:
    BATCH_SIZE: 2
    TRANSFORMS: True
  VAL:
    BATCH_SIZE: 2

MODEL:
  OUT_CH: 2  # for motion
  WEIGHTS: /path/to/state_dict.pth
  RECURRENT: True
