EXP:
  ROOT: /path/to/experiment_root
  NAME: motion

DATA:
  ROOT: /path/to/data_root
  NUM_WORKERS: 4
  TRAIN:
    BATCH_SIZE: 2
    TRANSFORMS: True
  VAL:
    BATCH_SIZE: 2

MODEL:
  OUT_CH: 2  # for motion
  RECURRENT: False
