# Args: <path_to_shape-net-core> <synset-id> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
  {
    "module": "main.Initializer",
    "config":{
      "global": {
        "output_dir": "<args:2>",
        "max_bounces": 200,
        "diffuse_bounces": 200,
        "glossy_bounces": 200,
        "transmission_bounces": 200,
        "transparency_bounces": 200
      }
    }
  },
  {
    "module": "loader.ShapeNetLoader",
    "config": {
      "data_path": "<args:0>",
      "used_synset_id": "<args:1>",
      "add_properties": {
        "cp_category_id": "1",
        "cp_cc_texture": True
      }
    }
  },
  {
    "module": "loader.CCMaterialLoader",
    # you can use the scripts/download_cc_textures.py to download them
    "config": {
      "folder_path": "/path/to/cctextures",
    }
  },
  {
    "module": "manipulators.WorldManipulator",
    "config": {
      "cf_set_world_category_id": 0  # this sets the worlds background category id to 0
    }
  },
  {
    "module": "lighting.LightSampler",
    "config": {
      "lights": [
      {
        "location": {
          "provider": "sampler.Shell",
          "center": [0, 0, -0.8],
          "radius_min": 2,
          "radius_max": 4,
          "elevation_min": 40,
          "elevation_max": 89
        },
        "type": "POINT",
        "energy": 1000
      }
      ]
    }
  },
  {
    "module": "manipulators.EntityManipulator",
    "config": {
      "selector": {
        "provider": "getter.Entity",
        "conditions": {
          "name": "model_normalized"
        }
      },
      "color": {
        "provider": "sampler.Color",
        "min": [ 0.1, 0.1, 0.1, 1.0 ],
        "max": [ 1.0, 1.0, 1.0, 1.0 ]
      },
      "cp_category_id": "1",
      "cf_randomize_materials": {
        "randomization_level": 0.,
        "materials_to_replace_with": {
          "provider": "getter.Material",
          "random_samples": 1,
          "conditions": {
            "cp_is_cc_texture": True  # this will return one random loaded cc textures
          }
        }
      },
      "cf_set_Roughness": {
        "provider": "sampler.Value",
        "type": "float",
        "min": 0.0,
        "max": 1.0,
      },
      "cf_set_Specular": {
        "provider": "sampler.Value",
        "type": "float",
        "min": 0.0,
        "max": 1.0,
      },
      "cf_color_link_to_displacement": {
        "provider": "sampler.Value",
        "type": "float",
        "min": 0.0,
        "max": 1.0,
      },
      "cf_set_Alpha": 1.0,
    }
  },
  {
    "module": "camera.CameraSampler",
    "config": {
      "cam_poses": [
      {
        "number_of_samples": 5,
        "location": {
          "provider": "sampler.Shell",
          "center": [ 0, 0, 0 ],
          "radius_min": 2,
          "radius_max": 2,
          "elevation_min": 5,
          "elevation_max": 89,
          "uniform_elevation": True
        },
        "rotation": {
          "format": "look_at",
          "value": {
            "provider": "getter.POI"
          }
        }
      }
      ]
    }
  },
  {
    "module": "manipulators.MaterialManipulator",
    "config": {
      "selector": {
        "provider": "getter.Material",
        "conditions": [{"name": ".*", use_nodes: True}]
      },
      "cf_set_Alpha": 1.0,
    }
  },
  {
    "module": "renderer.RgbRenderer",
    "config": {
      "render_normals": False,
      "samples": 350,
      "render_distance": False
    }
  },
  {
    "module": "renderer.SegMapRenderer",
    "config": {
      "use_alpha": True
    }
  },
  {
    "module": "writer.Hdf5Writer",
    "config": {
      "postprocessing_modules": {
        "distance": [
        {
          "module": "postprocessing.TrimRedundantChannels",
          "config": {}
        }
        ]
      }
    }
  }
  ]
}
